#!/usr/bin/env python3
from pybasic import lexer

import click


@click.command()
@click.argument('program', type=click.File('r'))
def main(program):
    lines = [line.strip() for line in program.readlines()]
    print([lexer.tokenize_line(line) for line in lines])

if __name__ == "__main__":
    main()
