#!/usr/bin/env python3
from pybasic import lexer
from pybasic import evaluator

import click


@click.command()
@click.argument('program', type=click.File('r'))
def main(program):
    lines = [line.strip() for line in program.readlines()]
    code_lines = [lexer.tokenize_line(line) for line in lines]
    evaluator.evaluate(code_lines)

if __name__ == "__main__":
    main()
